### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by ankush981** [donfour/committed2#2]
Hey, just wanted to say that you've done awesome work with this extension. I could find no other way to reach you and so sending a compliment as a GitHub issue. :smile: This was exactly what I wanted from my perfect ToDo extension -- no stupid redirecting to their websites, background wallpapers, and whatnot. :heart: 

By the way, why don't you start a Patreon profile for this? I'll be happy to pay $1 per month for this.

Thanks and keep rocking! :guitar:

**Comment by donfour** [comment]
@ankush981 Sorry for the late response! Thank you so much for the kind words. Honestly I don't think Committed deserves a Patreon page cause it's kind of an abandoned project right now (I'm not actively maintaining it or taking feature requests).

Anyways, thank you again for the comments!
